import AppCarousel from "@/components/AppCarousel";
import styles from "@/styles/Home.module.css";
import { Typography } from "@mui/material";
import Button from "@mui/material/Button";
import Paper from "@mui/material/Paper";
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Carol's Alterations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppCarousel />
        <Typography variant="h1">Home</Typography>
      </main>
    </>
  );
}
